[package]
name = "aptos_contract"
version = "1.0.0"
authors = []

[addresses]
aptos_contract = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.27.1"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.27.1"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]